USE master;
IF EXISTS (SELECT * FROM sys.databases WHERE name = 'ClientConnect')
BEGIN
    DROP DATABASE ClientConnect;
END

CREATE DATABASE ClientConnect;

USE ClientConnect;

CREATE TABLE Users (
    UserID INT PRIMARY KEY IDENTITY(1,1),
    FirstName VARCHAR(10) NOT NULL,
    LastName VARCHAR(10) NOT NULL,
    Email VARCHAR(50) NOT NULL UNIQUE,
    Password VARCHAR(255) NOT NULL,
    Role VARCHAR(20) CHECK (Role IN ('ADMIN', 'SM')),
    CreatedAt DATETIME DEFAULT GETDATE(),
    UserStatus VARCHAR(10) CHECK (UserStatus IN ('ACTIVE', 'INACTIVE'))
);

CREATE TABLE Customers (
	CID INT PRIMARY KEY IDENTITY(1,1),
	FirstName VARCHAR(10) NOT NULL,
	LastName VARCHAR(10) NOT NULL,
	Address TEXT,
	Company VARCHAR(50),
	CreatedBy INT,
	CustomerStatus VARCHAR(10) CHECK (CustomerStatus IN ('ACTIVE', 'INACTIVE')),
	Position VARCHAR(50),
	CreatedAt DATETIME DEFAULT GETDATE(),
	FOREIGN KEY (CreatedBy) REFERENCES Users(UserID)
);

CREATE TABLE Notes (
	NoteID INT PRIMARY KEY IDENTITY(1,1),
	Title VARCHAR(255) NOT NULL,
	Summary TEXT,
	Status VARCHAR(10) CHECK (Status IN ('COMPLETED','PENDING','CANCELLED')) DEFAULT 'PENDING',
	ExpectedCompletion DATETIME,
	CreatedBy INT,
	CreatedFor INT,
	CreatedAt DATETIME DEFAULT GETDATE(),
	FOREIGN KEY (CreatedBy) REFERENCES Users(UserID),
	FOREIGN KEY (CreatedFor) REFERENCES Customers(CID)
);

CREATE TABLE Phones (
	PID INT PRIMARY KEY IDENTITY(1,1),
	PhoneNumber BIGINT CHECK (PhoneNumber>=1000000000 AND PhoneNumber<=9999999999) UNIQUE NOT NULL,
	CID INT,
	FOREIGN KEY (CID) REFERENCES Customers(CID)
);

CREATE TABLE Emails (
	EID INT PRIMARY KEY IDENTITY(1,1),
	Email VARCHAR(255) UNIQUE NOT NULL,
	CID INT,
	FOREIGN KEY (CID) REFERENCES Customers(CID)
);

CREATE TABLE CustomerInteractions (
	CIID INT PRIMARY KEY IDENTITY(1,1),
	NoteID INT,
	UserID INT,
	InteractionTime DATETIME DEFAULT GETDATE(),
	FOREIGN KEY (NoteID) REFERENCES Notes(NoteID),
	FOREIGN KEY (UserID) REFERENCES Users(UserID)
);